language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
install:
  - npm install -g codeclimate-test-reporter
script:
  - npm run commitlint-travis
  - npm run lint
  - npm run coverage
after_success:
  - codeclimate < ./coverage/lcov.info
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
